### ISSUE TITLE
Error can't resolve 'crypto' in node_modules/hanif-midrans-node/dist/util.js

### ISSUE THREAD

**Issue by gudangcoding** [hansputera/midtrans-node#5]
saya mengalamai error penggunaan library ini dengan error seperti di bawah ini
Error: Module not found: Error: Can't resolve 'crypto' in 'D:\ionic\latihan1\node_modules\hanif-midtrans-node\dist\Util'

berikut kode app.module.ts saya
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouteReuseStrategy } from '@angular/router';

import { IonicModule, IonicRouteStrategy } from '@ionic/angular';

import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';
import { MidtransNode } from 'hanif-midtrans-node';

@NgModule({
  declarations: [AppComponent],
  imports: [ BrowserModule, IonicModule.forRoot(), AppRoutingModule],
  providers: [MidtransNode, { provide: RouteReuseStrategy, useClass: IonicRouteStrategy }],
  bootstrap: [AppComponent],
})
export class AppModule {}

dan seperti ini di halaman midtransya

import { Component, OnInit } from '@angular/core';
import { MidtransNode } from 'hanif-midtrans-node';
@Component({
  selector: 'app-midtrans-npm',
  templateUrl: './midtrans-npm.page.html',
  styleUrls: ['./midtrans-npm.page.scss'],
})
export class MidtransNPMPage implements OnInit {

  constructor() { }

  ngOnInit() {
  }

  bayar(){
    const midtrans = new MidtransNode(false, 'servey key saya'); // sandbox mode

    midtrans.createTransaction({
        transaction_details: {
            gross_amount: 20000, // IDR 20.000
            order_id: 'midtrans-node',
        },
    }).then(console.log).catch(console.error);
  }

}

<ion-header>
  <ion-toolbar>
    <ion-title>midtrans Node</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <ion-button (click)="bayar()" expand="block" fill="clear" shape="round">
    Bayar
  </ion-button>
</ion-content>

mohon bantuannya, dimanakah salah peletakan kode saya

**Comment by hansputera** [comment]
Module `crypto` dari node ngga ke deteksi jika di sisi browser/client, jadi harus berada di sisi server.

**Comment by hansputera** [comment]
Silahkan update ke v1.1.8 ya

Simple changelogs:
```diff
+ Now, we use `sha.js` module to generate SHA256 hash
+ define `struDate`, and `date` variables inside `HistoryTransaction` function (Iris)
```
